### ISSUE TITLE
Color Orange Possible ?

### ISSUE THREAD

**Issue by SulivanM** [lolcodingguru/ActionBarXtreme#1]
Hello !
I try in config file to put orange color, but nothing, can you add this ?

Best regards,
Sulivan

**Comment by lolcodingguru** [comment]
Hi Sulivan, 

Thanks for opening an issue. 

The Spigot API only supports a limited set of colors. If a color is not supported, there is nothing we can do about it. 

Unfortunately, orange is not one of the available colors. However, you can try using GOLD, which is close enough.

You can find the full list of colors supported by the Spigot API here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html

Sorry for any inconvenience caused by this,
codingGuru

**Comment by SulivanM** [comment]
Oh okay, thanks you !

**Comment by lolcodingguru** [comment]
You're welcome! I'm glad I could help. If you have any more questions or issues, feel free to open a new issue.

Also, if you enjoy using our plugin, we would really appreciate it if you could take a moment to leave a review on SpigotMC. Thank you for your support!

Have a great day!
